### ISSUE TITLE
Incorrect Semantic Token Type Using LibFmt

### ISSUE THREAD

**Issue by daiyousei-qz** [clangd/clangd#1096]
```
#define FMT_HEADER_ONLY
#include <fmt/format.h>

enum class TestEnum
{
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
};

template <typename FormatContext>
static auto FormatEnum(const TestEnum& type, FormatContext& ctx) -> decltype(ctx.out())
{
    switch (type)
    {
    case TestEnum::E1:
        return fmt::format_to(ctx.out(), "1");
    case TestEnum::E2:
        return fmt::format_to(ctx.out(), "2");
    case TestEnum::E3:
        return fmt::format_to(ctx.out(), "3");
    case TestEnum::E4:
        return fmt::format_to(ctx.out(), "4");
    case TestEnum::E5:
        return fmt::format_to(ctx.out(), "5");
    case TestEnum::E6:
        return fmt::format_to(ctx.out(), "6");
    }
}
```

Some function calls are not labelled with correct semantic token type:
![image](https://user-images.githubusercontent.com/12378019/162117140-9e28b0c3-a593-4c65-866a-90f921670ebd.png)

However, hover window seems to work correctly:
![image](https://user-images.githubusercontent.com/12378019/162117281-ea616686-1b27-4827-b8ff-49f4f7dfcec4.png)

The following is a self-contained repro including libfmt headers and compile_commands.json
[clangd_bug.zip](https://github.com/clangd/clangd/files/8439517/clangd_bug.zip)

**System information**

Output of `clangd --version`: clangd-14

Editor/LSP plugin: vscode 1.66.0

Operating system: WSL2 Ubuntu 20.04

**Comment by HighCommander4** [comment]
Strange, seems to work for me:

![Screenshot_20220407_013132](https://user-images.githubusercontent.com/1751085/162127169-057cf7fe-b432-4ba5-bffa-e636176068c0.png)

**Comment by HighCommander4** [comment]
Can you try the following please:

 * Select the `return fmt::format_to(ctx.out(), "1");` line
 * Run F1 > "clangd: Show AST"
 * Share a screenshot of the "AST" view that comes up

**Comment by HighCommander4** [comment]
(It occurred to me that maybe this is #1057 which I fixed recently on trunk, but I tested with clangd-14 which doesn't contain that fix and it works there too.)

**Comment by daiyousei-qz** [comment]
I just downloaded a fresh llvm14 copy from the github release page, and the problem persists. I was using gcc, but switched to clang in the copy I just downloaded for compile_commands.json

Here's the AST for return at case E1:
![image](https://user-images.githubusercontent.com/12378019/162134816-3620772e-edf1-4f56-b720-0d389f540064.png)

Interestingly, for case E2, it shows exactly the same AST with a UnresolvedLookup though the function name is colored correctly.
![image](https://user-images.githubusercontent.com/12378019/162135022-d9f83102-bdbb-4eee-aa8d-86c375fa773c.png)

It may also be worth noting is that, if I copy the clangd binary to a separate folder and use it stand alone, all function names are identified. But AST is still unresolved lookup.
![image](https://user-images.githubusercontent.com/12378019/162134509-44cb71ba-8088-4bfd-9953-cce347125c57.png)

**Comment by daiyousei-qz** [comment]
This doesn't seem to be related to switch, I can repro with the following
![image](https://user-images.githubusercontent.com/12378019/162138339-87d53a82-901b-428c-b5fe-47e12c1fda73.png)

```
qingyuanz@QingyuanZ-PC ~/clangd_bug> /home/qingyuanz/tools/llvm14/bin/clangd --version
clangd version 14.0.0
Features: linux
Platform: x86_64-unknown-linux-gnu
```

**Comment by daiyousei-qz** [comment]
I have created a minimal repro with no external dependency. It seems this is related to the use of [[deprecated]] attribute.
![image](https://user-images.githubusercontent.com/12378019/162512323-4e09f18d-4e05-403d-8b58-01b0c6905c82.png)
![image](https://user-images.githubusercontent.com/12378019/162512470-ede05ad4-2fc7-4bed-a680-00e924e47e8d.png)
![image](https://user-images.githubusercontent.com/12378019/162513003-b93a1a75-2d72-4873-b712-c42939976fce.png)

Adding other AST nodes between those Foo() function will also affect how they are colored in Bar.

**Comment by HighCommander4** [comment]
Can you post the contents of the screenshots as text please?

**Comment by HighCommander4** [comment]
Additionally, it would be interesting to see a clangd log, taken with `--log=verbose` in `"clangd.arguments"` (the log is visible in the Output view, choose "clangd" from the dropdown), for one of these minimal repros.

**Comment by daiyousei-qz** [comment]
No problem.

```
void Foo() {
}

[[deprecated]] void Foo(int* x) {
}

void Foo(int x) {
}

template <typename T>
void Bar(T x)
{
    Foo(x); 
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
    Foo(x);
}
```

**Comment by daiyousei-qz** [comment]
Here's the arguments:
```
    "clangd.arguments": [
        "--background-index",
        // "--inlay-hints",
        "--clang-tidy",
        "--cross-file-rename",
        "--header-insertion=never",
        "--compile-commands-dir=${workspaceFolder}/build",
        "-log=verbose",
        "-j=8"
    ],
```

Here's the clangd's log
```
The flag `-cross-file-rename` is obsolete and ignored.
I[21:28:41.512] clangd version 14.0.0
I[21:28:41.512] Features: linux
I[21:28:41.512] PID: 31256
I[21:28:41.513] Working directory: /home/qingyuanz/clangd_bug
I[21:28:41.513] argv[0]: /home/qingyuanz/tools/llvm14/bin/clangd
I[21:28:41.513] argv[1]: --background-index
I[21:28:41.513] argv[2]: --clang-tidy
I[21:28:41.513] argv[3]: --cross-file-rename
I[21:28:41.513] argv[4]: --header-insertion=never
I[21:28:41.513] argv[5]: --compile-commands-dir=/home/qingyuanz/clangd_bug/build
I[21:28:41.513] argv[6]: -log=verbose
I[21:28:41.513] argv[7]: -j=8
V[21:28:41.513] User config file is /home/qingyuanz/.config/clangd/config.yaml
I[21:28:41.513] Starting LSP over stdin/stdout
V[21:28:41.521] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Visual Studio Code","version":"1.66.1"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"locale":"en","processId":31188,"rootPath":"/home/qingyuanz/clangd_bug","rootUri":"file:///home/qingyuanz/clangd_bug","trace":"off","workspaceFolders":[{"name":"clangd_bug","uri":"file:///home/qingyuanz/clangd_bug"}]}}

I[21:28:41.521] <-- initialize(0)
I[21:28:41.522] --> reply:initialize(0) 0 ms
V[21:28:41.522] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"clangdInlayHintsProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/","*"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","deprecated","deduced","readonly","static","abstract","virtual","dependentName","defaultLibrary","usedAsMutableReference","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",")","{","}","<",">",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeDefinitionProvider":true,"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 14.0.0 linux x86_64-unknown-linux-gnu"}}}

V[21:28:41.593] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[21:28:41.593] <-- initialized
V[21:28:41.593] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"\nvoid Foo() {\n}\n\n[[deprecated]] void Foo(int* x) {\n}\n\nvoid Foo(int x) {\n}\n\ntemplate <typename T>\nvoid Bar(T x)\n{\n    Foo(x); \n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n    Foo(x);\n}","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp","version":1}}}

I[21:28:41.593] <-- textDocument/didOpen
V[21:28:41.594] <<< {"id":1,"jsonrpc":"2.0","method":"clangd/inlayHints","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.594] <-- clangd/inlayHints(1)
I[21:28:41.596] Loaded compilation database from /home/qingyuanz/clangd_bug/build/compile_commands.json
V[21:28:41.596] Broadcasting compilation database from /home/qingyuanz/clangd_bug/build
I[21:28:41.596] --> window/workDoneProgress/create(0)
V[21:28:41.596] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}

I[21:28:41.596] ASTWorker building file /home/qingyuanz/clangd_bug/src/main.cpp version 1 with command 
[/home/qingyuanz/clangd_bug/build]
/home/qingyuanz/tools/llvm14/bin/clang++ --driver-mode=g++ -I/home/qingyuanz/clangd_bug/include -g -std=c++20 -o CMakeFiles/App.dir/src/main.cpp.o -c -resource-dir=/home/qingyuanz/tools/llvm14/lib/clang/14.0.0 -- /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.596] Enqueueing 1 commands for indexing
V[21:28:41.596] BackgroundIndex: building version 1 after loading index from disk
V[21:28:41.596] BackgroundIndex: serving version 1 (16616 bytes)
V[21:28:41.610] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/qingyuanz/clangd_bug/build -resource-dir /home/qingyuanz/tools/llvm14/lib/clang/14.0.0 -I /home/qingyuanz/clangd_bug/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward -internal-isystem /home/qingyuanz/tools/llvm14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/qingyuanz/clangd_bug/build -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.610] --> textDocument/clangd.fileStatus
V[21:28:41.610] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Update (1)","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:41.610] Building first preamble for /home/qingyuanz/clangd_bug/src/main.cpp version 1
V[21:28:41.615] indexed preamble AST for /home/qingyuanz/clangd_bug/src/main.cpp version 1:
  symbol slab: 0 symbols, 120 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 0 relations, 24 bytes
V[21:28:41.616] Built preamble of size 224952 for file /home/qingyuanz/clangd_bug/src/main.cpp version 1
I[21:28:41.616] --> workspace/semanticTokens/refresh(1)
V[21:28:41.616] >>> {"id":1,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}

I[21:28:41.616] --> textDocument/clangd.fileStatus
V[21:28:41.616] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:41.643] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":11,"line":16},"start":{"character":11,"line":16}},"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.643] <-- textDocument/codeAction(2)
V[21:28:41.643] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":1}}

I[21:28:41.643] <-- $/cancelRequest
V[21:28:41.643] <<< {"id":3,"jsonrpc":"2.0","method":"clangd/inlayHints","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.643] <-- clangd/inlayHints(3)
V[21:28:41.653] indexed file AST for /home/qingyuanz/clangd_bug/src/main.cpp version 1:
  symbol slab: 4 symbols, 5144 bytes
  ref slab: 4 symbols, 37 refs, 4320 bytes
  relations slab: 0 relations, 24 bytes
V[21:28:41.653] Build dynamic index for main-file symbols with estimated memory usage of 14136 bytes
I[21:28:41.653] --> textDocument/publishDiagnostics
V[21:28:41.653] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp","version":1}}

I[21:28:41.653] --> reply:clangd/inlayHints(1) 59 ms, error: Task was cancelled.
V[21:28:41.653] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":1,"jsonrpc":"2.0"}

V[21:28:41.653] ASTWorker running EnumerateTweaks on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.653] --> reply:textDocument/codeAction(2) 10 ms
V[21:28:41.653] >>> {"id":2,"jsonrpc":"2.0","result":[]}

V[21:28:41.653] ASTWorker running InlayHints on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.653] --> reply:clangd/inlayHints(3) 10 ms
V[21:28:41.653] >>> {"id":3,"jsonrpc":"2.0","result":[]}

I[21:28:41.653] --> textDocument/clangd.fileStatus
V[21:28:41.653] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:41.675] <<< {"id":0,"jsonrpc":"2.0","result":null}

I[21:28:41.675] <-- reply(0)
I[21:28:41.675] --> $/progress
V[21:28:41.675] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"begin","percentage":0,"title":"indexing"}}}

I[21:28:41.675] --> $/progress
V[21:28:41.675] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"end"}}}

V[21:28:41.675] <<< {"id":4,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.675] <-- textDocument/documentLink(4)
V[21:28:41.675] ASTWorker running DocumentLinks on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.675] --> reply:textDocument/documentLink(4) 0 ms
V[21:28:41.675] >>> {"id":4,"jsonrpc":"2.0","result":[]}

I[21:28:41.675] --> textDocument/clangd.fileStatus
V[21:28:41.675] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:41.675] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":4}}

I[21:28:41.675] <-- $/cancelRequest
V[21:28:41.676] <<< {"id":5,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.676] <-- textDocument/documentLink(5)
V[21:28:41.676] ASTWorker running DocumentLinks on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.676] --> reply:textDocument/documentLink(5) 0 ms
V[21:28:41.676] >>> {"id":5,"jsonrpc":"2.0","result":[]}

I[21:28:41.676] --> textDocument/clangd.fileStatus
V[21:28:41.676] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:41.676] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":3}}

I[21:28:41.676] <-- $/cancelRequest
V[21:28:41.676] <<< {"id":6,"jsonrpc":"2.0","method":"clangd/inlayHints","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.676] <-- clangd/inlayHints(6)
V[21:28:41.676] ASTWorker running InlayHints on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.676] --> reply:clangd/inlayHints(6) 0 ms
V[21:28:41.676] >>> {"id":6,"jsonrpc":"2.0","result":[]}

I[21:28:41.676] --> textDocument/clangd.fileStatus
V[21:28:41.676] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:41.685] <<< {"id":1,"jsonrpc":"2.0","result":null}

I[21:28:41.685] <-- reply(1)
V[21:28:41.702] <<< {"id":7,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:41.702] <-- textDocument/semanticTokens/full(7)
V[21:28:41.702] ASTWorker running SemanticHighlights on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:41.702] --> reply:textDocument/semanticTokens/full(7) 0 ms
V[21:28:41.702] >>> {"id":7,"jsonrpc":"2.0","result":{"data":[1,5,3,3,8193,3,20,3,3,8195,0,9,1,2,1025,3,5,3,3,8193,0,8,1,2,1025,3,19,1,16,1025,1,5,3,3,8193,0,4,1,16,1024,0,2,1,2,1025,2,8,1,2,1024,1,4,3,3,8194,0,4,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024,1,8,1,2,1024],"resultId":"1"}}

I[21:28:41.702] --> textDocument/clangd.fileStatus
V[21:28:41.702] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:42.632] <<< {"id":8,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":11,"line":16},"start":{"character":11,"line":16}},"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:42.632] <-- textDocument/codeAction(8)
V[21:28:42.632] ASTWorker running EnumerateTweaks on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:42.632] --> reply:textDocument/codeAction(8) 0 ms
V[21:28:42.632] >>> {"id":8,"jsonrpc":"2.0","result":[]}

I[21:28:42.632] --> textDocument/clangd.fileStatus
V[21:28:42.632] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}

V[21:28:42.662] <<< {"id":9,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}}

I[21:28:42.662] <-- textDocument/documentSymbol(9)
V[21:28:42.662] ASTWorker running DocumentSymbols on version 1 of /home/qingyuanz/clangd_bug/src/main.cpp
I[21:28:42.662] --> reply:textDocument/documentSymbol(9) 0 ms
V[21:28:42.662] >>> {"id":9,"jsonrpc":"2.0","result":[{"detail":"void ()","kind":12,"name":"Foo","range":{"end":{"character":1,"line":2},"start":{"character":0,"line":1}},"selectionRange":{"end":{"character":8,"line":1},"start":{"character":5,"line":1}}},{"deprecated":true,"detail":"void (int *)","kind":12,"name":"Foo","range":{"end":{"character":1,"line":5},"start":{"character":15,"line":4}},"selectionRange":{"end":{"character":23,"line":4},"start":{"character":20,"line":4}}},{"detail":"void (int)","kind":12,"name":"Foo","range":{"end":{"character":1,"line":8},"start":{"character":0,"line":7}},"selectionRange":{"end":{"character":8,"line":7},"start":{"character":5,"line":7}}},{"detail":"template void (T)","kind":12,"name":"Bar","range":{"end":{"character":1,"line":24},"start":{"character":0,"line":11}},"selectionRange":{"end":{"character":8,"line":11},"start":{"character":5,"line":11}}}]}

I[21:28:42.662] --> textDocument/clangd.fileStatus
V[21:28:42.662] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///home/qingyuanz/clangd_bug/src/main.cpp"}}
```

**Comment by HighCommander4** [comment]
Thanks, I can reproduce the issue locally with the code from [this comment](https://github.com/clangd/clangd/issues/1096#issuecomment-1094173523).

Based on the logs, it does look like clangd is sending incorrect semantic tokens, i.e. it's a bug on the clangd side.

**Comment by HighCommander4** [comment]
Well, the good news is that this is in fact fixed on trunk by #1057. You can download a weekly snapshot release from https://github.com/clangd/clangd/releases to access the fix prior to the LLVM 15 release.

However, I think there is an underlying bug here which the fix for #1057 hides rather than fixes. The reason #1057 fixes the symptoms here is that for each of the calls, we're supposed to get three candidate highlighting tokens (one for each overload of `Foo()`), and prior to #1057 we would drop the tokens if there were three or more candidates. However, what's actually happening is that for some of the calls, we only get **two** candidate tokens (those are the cases where the highlighting works prior to #1057), which makes no sense -- they're identical calls, so they're uspposed to get the same candidate tokens.

**Comment by HighCommander4** [comment]
There's a bug in `HighlightingToken`'s [`operator<`](https://searchfox.org/llvm/rev/88ff6f70c45f2767576c64dde28cbfe7a90916ca/clang-tools-extra/clangd/SemanticHighlighting.cpp#914):

```
bool operator<(const HighlightingToken &L, const HighlightingToken &R) {
  return std::tie(L.R, L.Kind, R.Modifiers) <
         std::tie(R.R, R.Kind, R.Modifiers);
}
```

The first line should be using `L.Modifiers`.

As a result, the sort/unique pass on the tokens is unreliable. Two of the three candidate tokens are identical (the third has the deprecated modifier), so a correct sort/unique pass should collapse them to two candidate tokens.

**Comment by HighCommander4** [comment]
[Fix](https://reviews.llvm.org/D123478)
