### ISSUE TITLE
Add a semantic highlighting for macro names

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#134]
Macro names are one of the few remaining types of tokens which do not get a semantic highlighting (besides keywords, which are typically colored lexically by editors). It would be nice to add a highlighting for them.

cc @jvikstrom

**Comment by hokein** [comment]
Fixed in rL370482 and rL371504.

**Comment by HighCommander4** [comment]
It looks like macro references in preprocessor directives are still not highlighted:

```
#define WALDO  // highlighted

#ifdef WALDO    // not highlighted
int x;
#else

#endif
```

**Comment by hokein** [comment]
We were missing them, fixed in 373889.
