### ISSUE TITLE
clang crashes on code completion.

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#332]
another clang crash:

```
class Foo {
public:
  Foo() : s(foo(^));
};

// comment no newline below.
```

crash stack:

```
clangd: llvm-project/clang/lib/AST/RawCommentList.cpp:167: llvm::StringRef clang::RawComment::getRawTextSlow(const clang::SourceManager &) const: Assertion `BeginFileID == EndFileID' failed.
 #0 0x00000000004e954f llvm::sys::PrintStackTrace(llvm::raw_ostream&) llvm-project/llvm/lib/Support/Unix/Signals.inc:564:13
 #1 0x00000000004e7772 llvm::sys::RunSignalHandlers() llvm-project/llvm/lib/Support/Signals.cpp:69:18
 #2 0x00000000004e989c SignalHandler(int) llvm-project/llvm/lib/Support/Unix/Signals.inc:396:3
 #3 0x00007fb0c2739520 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13520)
 #4 0x00007fb0c2209081 raise /build/glibc-QG9qOO/glibc-2.29/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007fb0c21f4535 abort /build/glibc-QG9qOO/glibc-2.29/stdlib/abort.c:81:7
 #6 0x00007fb0c21f440f _nl_load_domain /build/glibc-QG9qOO/glibc-2.29/intl/loadmsgcat.c:1177:9
 #7 0x00007fb0c2201b92 (/lib/x86_64-linux-gnu/libc.so.6+0x32b92)
 #8 0x000000000073bd5f (llvm-project/build/bin/clangd+0x73bd5f)
 #9 0x000000000073ba20 clang::RawComment::getRawText(clang::SourceManager const&) const llvm-project/clang/include/clang/AST/RawCommentList.h:102:13
#10 0x000000000073ba20 clang::RawComment::RawComment(clang::SourceManager const&, clang::SourceRange, clang::CommentOptions const&, bool) llvm-project/clang/lib/AST/RawCommentList.cpp:115:0
#11 0x00000000014084aa clang::RawComment::isAlmostTrailingComment() const llvm-project/clang/include/clang/AST/RawCommentList.h:84:12
#12 0x00000000014084aa clang::Sema::ActOnComment(clang::SourceRange) llvm-project/clang/lib/Sema/Sema.cpp:2005:0
#13 0x00000000011c70cd (anonymous namespace)::ActionCommentHandler::HandleComment(clang::Preprocessor&, clang::SourceRange) llvm-project/clang/lib/Parse/Parser.cpp:38:5
#14 0x000000000093885f clang::Preprocessor::HandleComment(clang::Token&, clang::SourceRange) llvm-project/clang/lib/Lex/Preprocessor.cpp:1399:15
#15 0x00000000008f1c25 clang::Lexer::SkipLineComment(clang::Token&, char const*, bool&) llvm-project/clang/lib/Lex/Lexer.cpp:2357:7
#16 0x00000000008f71db clang::Lexer::LexTokenInternal(clang::Token&, bool) llvm-project/clang/lib/Lex/Lexer.cpp:0:41
#17 0x00000000008f2cf2 clang::Lexer::Lex(clang::Token&) llvm-project/clang/lib/Lex/Lexer.cpp:3171:3
#18 0x0000000000937295 clang::Preprocessor::Lex(clang::Token&) llvm-project/clang/lib/Lex/Preprocessor.cpp:909:13
#19 0x00000000011c12c6 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) llvm-project/clang/lib/Parse/Parser.cpp:1042:17
#20 0x00000000011c0b9c clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) llvm-project/clang/lib/Parse/Parser.cpp:1114:12
#21 0x00000000011bfc61 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) llvm-project/clang/lib/Parse/Parser.cpp:934:12
#22 0x00000000011bdcb4 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) llvm-project/clang/lib/Parse/Parser.cpp:685:10
#23 0x00000000011bd567 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) llvm-project/clang/lib/Parse/Parser.cpp:555:26
#24 0x00000000011b92cf clang::ParseAST(clang::Sema&, bool, bool) llvm-project/clang/lib/Parse/ParseAST.cpp:157:25
#25 0x00000000010716e1 clang::FrontendAction::Execute() llvm-project/clang/lib/Frontend/FrontendAction.cpp:944:10
#26 0x00000000009e4345 llvm::Error::getPtr() const llvm-project/llvm/include/llvm/Support/Error.h:273:42
#27 0x00000000009e4345 llvm::Error::operator bool() llvm-project/llvm/include/llvm/Support/Error.h:236:0
#28 0x00000000009e4345 clang::clangd::(anonymous namespace)::semaCodeComplete(std::unique_ptr<clang::CodeCompleteConsumer, std::default_delete<clang::CodeCompleteConsumer> >, clang::CodeCompleteOptions const&, clang::clangd::(anonymous namespace)::SemaCompleteInput const&, clang::clangd::IncludeStructure*) llvm-project/clang-tools-extra/clangd/CodeComplete.cpp:1123:0
#29 0x00000000009e2d7d std::unique_ptr<clang::CodeCompleteConsumer, std::default_delete<clang::CodeCompleteConsumer> >::~unique_ptr() /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:283:6
#30 0x00000000009e2d7d clang::clangd::(anonymous namespace)::CodeCompleteFlow::run(clang::clangd::(anonymous namespace)::SemaCompleteInput const&) && llvm-project/clang-tools-extra/clangd/CodeComplete.cpp:1315:0
#31 0x00000000009e2d7d clang::clangd::codeComplete(llvm::StringRef, clang::tooling::CompileCommand const&, clang::clangd::PreambleData const*, llvm::StringRef, clang::clangd::Position, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, clang::clangd::CodeCompleteOptions, clang::clangd::SpeculativeFuzzyFind*) llvm-project/clang-tools-extra/clangd/CodeComplete.cpp:1757:0
#32 0x00000000009d7f69 std::_Function_base::~_Function_base() /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:259:11
#33 0x00000000009d7f69 clang::clangd::CodeCompleteOptions::~CodeCompleteOptions() llvm-project/clang-tools-extra/clangd/CodeComplete.h:42:0
```

**Comment by kadircet** [comment]
i believe this has also been fixed in the meanwhile. couldn't repro wih a clangd built from head, closing it. please re-open if you can repro.

**Comment by hokein** [comment]
I encountered this recently. The crash still happens with the sample case, trying to come up with a fix.

**Comment by hokein** [comment]
The issue is caused by the discrepancy between the offset viewed in SourceManager and the content buffer viewed in the clang parser, we're getting a problematic end location of the main file during the code completion, which points to another file! 

Code-completion is performed in the following way:
1) SourceManager is initialized in `clang::FrontendAction::BeginSourceFile` -- this means we load the raw buffer into SM, and local offsets are set;
2) the we setup code completion in `clang::FrontendAction::Execute` -- this includes modified the raw main-file buffer by inserting an extra `\0` character at the code completion point, and then [override](https://github.com/llvm/llvm-project/blob/main/clang/lib/Lex/Preprocessor.cpp#L387) the original raw buffer in SM

The problem is that the override operation in step2 doesn't update the local offset in SM. And it is tricky and scary to do so.

A simple fix is to preserve 1 more byte when allocating the offset space for the file buffer in SM (+2 [here](https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/SourceManager.cpp#L624)), it does fix the issue, but it breaks a bunch of existing tests -- it looks like many places rely on the fact that the `start+filesize+1` offset is the end location of the file :(

Another idea is to use the modified content to initialize the SourceManager, it might be a bit of work.
