### ISSUE TITLE
Template parameters are displayed incorrectly

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#76]
Template parameters are not displayed correctly when hovering over the constructor.

1.code
```c++
template<class T>
struct Test {
    Test() {}
};

template<class T>
struct Test<T *> {
    Test() {}
//  ^^^^     hover on test
};
```
2.screenshot
![image](https://user-images.githubusercontent.com/10697249/60657982-d94bb580-9e84-11e9-99b5-ad8fbb97811d.png)

**Comment by lh123** [comment]
The template parameters in the outline and signature help are also incorrect.

**Comment by sam-mccall** [comment]
I think this is now done as originally reported, albeit by not printing the template params in most cases.

That said I think the hover screenshot should say "Declared in `Test<T *>`", so leaving open for now.

**Comment by lh123** [comment]
+ clangd version: `10.0.0 (https://github.com/llvm/llvm-project.git 905b002c139f039a32ab9bf1fad63d745d12423f)`

```c++
template<typename T>
struct Test {};

template<typename T>
struct Test<T *> {
  Test(int a);
};


int main() {
  Test<int *> a();
}

```
I think this problem still occur in the signature.
![image](https://user-images.githubusercontent.com/10697249/69910416-36549300-1446-11ea-9481-14b9757b6fd9.png)

**Comment by HighCommander4** [comment]
Confirmed, reopening.

**Comment by lh123** [comment]
It's also occur in `LocalScope`.
```c++
template<typename T, typename = int>
struct Test {
void test();
};

int main() {
    Test<int> a;
    a.test();
}
```
![Screenshot_20191208_175121](https://user-images.githubusercontent.com/10697249/70387717-6ae6c280-19e3-11ea-849e-eb53124c6f9b.png)

**Comment by kadircet** [comment]
it should be fixed, please let me know if it is still the case.

**Comment by lh123** [comment]
@kadircet 
`clangd version 10.0.0 (https://github.com/llvm/llvm-project.git f041e9ad706aee7987c5299427c33424fcabbd0d)`
still occur in the signature.
![image](https://user-images.githubusercontent.com/10697249/72153832-ef18d500-33e9-11ea-8f32-92007a3816ce.png)

**Comment by kadircet** [comment]
ah right, sent https://reviews.llvm.org/D72715
